name: Check

on:
  push:
    branches: [ main ]
    paths:
      - '**.kt'
      - '**.kts'
      - '**.cpp'
      - 'gradle.properties'
      - '.github/workflows/check.yml'
      - 'gradle/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.kt'
      - '**.kts'
      - '**.cpp'
      - 'gradle.properties'
      - '.github/workflows/check.yml'
      - 'gradle/**'
  workflow_dispatch:

jobs:
  check:
    name: "Check"
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            deps-cmd: sudo apt install mpv
          - os: macos-latest
            deps-cmd: brew install mpv
          - os: windows-latest
            deps-cmd: choco install mpv
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ vars.JVM_DISTRIBUTION }}
          java-version: ${{ vars.JVM_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v4

      - name: Install dependencies 
        run: ${{ runner.deps-cmd }}

      - name: Cache konan directory
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: "${{ runner.os }}-konan-"

      - name: Check
        run: ./gradlew check
